# Generated by Django 3.2.7 on 2022-05-18 07:37

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import film_places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilmPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FilmPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo_camera', models.CharField(max_length=40)),
                ('cost', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=40)),
                ('place_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('string_place_location', models.CharField(blank=True, max_length=40, null=True)),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_ip_user', models.CharField(blank=True, max_length=18, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('was_added', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('category', models.ManyToManyField(to='film_places.CategoryFilmPlaces')),
                ('main_photo', models.ForeignKey(blank=True, null=True, on_delete=models.SET(film_places.models.get_photo), related_name='film_places_main_photo', to='gallery.image')),
                ('place_image', models.ManyToManyField(to='gallery.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='NotAuthFilmRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filming_timestamp', models.DateTimeField()),
                ('hours_duration', models.CharField(max_length=40)),
                ('filming_type', models.CharField(max_length=40)),
                ('count_person', models.CharField(max_length=40)),
                ('filming_budget', models.CharField(max_length=40)),
                ('need_makeup_artist', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('was_added', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('place_filming', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('email_verify', models.BooleanField(default=False)),
                ('email_code', models.CharField(max_length=40)),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_auth_request_receiver_profile', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FilmRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filming_timestamp', models.DateTimeField()),
                ('hours_duration', models.CharField(max_length=40)),
                ('filming_type', models.CharField(max_length=40)),
                ('filming_status', models.CharField(choices=[('NEW', 'Новый'), ('ACCEPTED', 'Принят'), ('COMPLETED', 'Завершен'), ('UNCOMPLETED', 'Не завершен'), ('REJECTED', 'Отклонен')], default='NEW', max_length=12)),
                ('count_person', models.CharField(max_length=40)),
                ('filming_budget', models.CharField(max_length=40)),
                ('need_makeup_artist', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('was_added', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('place_filming', models.CharField(max_length=40, null=True)),
                ('reason_failure', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender_profile', to='accounts.profile')),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver_profile', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FilmPlacesLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_places.filmplaces')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FilmPlacesFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_places.filmplaces')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FilmPlacesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('answer_id_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_places_comment_answer', to='film_places.filmplacescomment')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_places.filmplaces')),
                ('quote_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_places_comment_quote', to='film_places.filmplacescomment')),
                ('sender_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
