# Generated by Django 3.2.7 on 2022-10-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_places', '0003_rename_likes_filmplaces_likesstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmplaces',
            name='likesStat',
        ),
    ]
