# Generated by Django 3.2.7 on 2021-12-09 17:46

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_register', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('last_date_in', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=15)),
                ('filming_geo', models.CharField(blank=True, max_length=100)),
                ('work_condition', models.CharField(blank=True, max_length=100)),
                ('cost_services', models.CharField(blank=True, max_length=100)),
                ('photo_technics', models.CharField(blank=True, max_length=50)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('type_pro_account', models.IntegerField(default=1, null=True)),
                ('expired_pro_subscription', models.DateTimeField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('site', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('email_verify', models.BooleanField(default=False)),
                ('instagram', models.CharField(blank=True, max_length=40)),
                ('facebook', models.CharField(blank=True, max_length=40)),
                ('vk', models.CharField(blank=True, max_length=40)),
                ('location_now', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_stay_start', models.DateTimeField(blank=True, null=True)),
                ('date_stay_end', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('is_show_nu_photo', models.BooleanField(default=False)),
                ('type_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.procategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.IntegerField(blank=True, null=True)),
                ('profile_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='procategory',
            name='spec_model_or_photographer',
            field=models.ManyToManyField(blank=True, to='accounts.Specialization'),
        ),
    ]
