# Generated by Django 3.2.7 on 2021-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
