# Generated by Django 3.2.7 on 2022-05-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filming_geo',
            field=models.ManyToManyField(blank=True, to='additional_entities.Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='additional_entities.Language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spec_model_or_photographer',
            field=models.ManyToManyField(blank=True, to='accounts.Specialization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.procategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
