# Generated by Django 3.2.7 on 2022-10-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220518_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
