# Generated by Django 3.2.7 on 2022-10-21 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
