# Generated by Django 3.2.7 on 2023-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='_accounts_profile_team_+', to='accounts.Profile'),
        ),
    ]
