# Generated by Django 3.2.7 on 2023-01-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AWAITING', 'Ожидает'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='AWAITING', max_length=12)),
                ('invite_receiver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to='accounts.profile')),
                ('invite_sender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to='accounts.profile')),
            ],
        ),
    ]
