# Generated by Django 3.2.7 on 2023-01-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teaminvites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvites',
            name='invite_receiver',
        ),
        migrations.AddField(
            model_name='teaminvites',
            name='invite_receiver',
            field=models.ManyToManyField(null=True, related_name='invite_receiver', to='accounts.Profile'),
        ),
        migrations.RemoveField(
            model_name='teaminvites',
            name='invite_sender',
        ),
        migrations.AddField(
            model_name='teaminvites',
            name='invite_sender',
            field=models.ManyToManyField(null=True, related_name='invite_sender', to='accounts.Profile'),
        ),
    ]
