# Generated by Django 3.2.7 on 2023-01-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230118_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvites',
            name='invite_receiver',
        ),
        migrations.AddField(
            model_name='teaminvites',
            name='invite_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='teaminvites',
            name='invite_sender',
        ),
        migrations.AddField(
            model_name='teaminvites',
            name='invite_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to='accounts.profile'),
        ),
    ]
