# Generated by Django 3.2.7 on 2023-02-01 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230118_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('status', models.CharField(choices=[('NEW_LIKE', 'Новый лайк'), ('NEW_COMMENT', 'Новый комментарий'), ('NEW_FAVORITE', 'Новое добавление в избранное'), ('NEW_MESSAGE', 'Новое сообщение'), ('NEW_FILMING_REQUEST', 'Новый запрос на съемку'), ('NEW_TRAINING_REQUEST', 'Новый запрос на обучение'), ('NEW_TEAM_REQUEST', 'Новый запрос в команду')], default='AWAITING', max_length=20)),
                ('action_position', models.IntegerField(null=True)),
                ('receiver_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_receiver_profile', to='accounts.profile')),
                ('sender_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_sender_profile', to='accounts.profile')),
            ],
        ),
    ]
