# Generated by Django 3.2.7 on 2023-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='status',
            new_name='type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='readen',
            field=models.BooleanField(default=False),
        ),
    ]
