# Generated by Django 3.2.7 on 2023-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('NEW_LIKE', 'Новый лайк'), ('NEW_COMMENT', 'Новый комментарий'), ('NEW_FAVORITE', 'Новое добавление в избранное'), ('NEW_MESSAGE', 'Новое сообщение'), ('NEW_FILMING_REQUEST', 'Новый запрос на съемку'), ('NEW_TRAINING_REQUEST', 'Новый запрос на обучение'), ('NEW_TEAM_REQUEST', 'Новый запрос в команду')], max_length=20),
        ),
    ]
