# Generated by Django 3.2.7 on 2023-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notifications_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('NEW_SESSION_LIKE', 'Новый лайк фотосессии'), ('NEW_SESSION_COMMENT', 'Новый комментарий к фотосессии'), ('NEW_SESSION_FAVORITE', 'Новое добавление фотосессии в избранное'), ('NEW_PHOTO_LIKE', 'Новый лайк фотографии'), ('NEW_PHOTO_COMMENT', 'Новый комментарий к фотографии'), ('NEW_PHOTO_FAVORITE', 'Новое добавление фотографии в избранное'), ('NEW_PLACE_LIKE', 'Новый лайк места для съемки'), ('NEW_PLACE_COMMENT', 'Новый комментарий к месту для съемки'), ('NEW_PLACE_FAVORITE', 'Новое добавление места для съемки в избранное'), ('NEW_TRAINING_LIKE', 'Новый лайк обучения'), ('NEW_TRAINING_COMMENT', 'Новый комментарий к обучению'), ('NEW_TRAINING_FAVORITE', 'Новое добавление обучения в избранное'), ('NEW_MESSAGE', 'Новое сообщение'), ('NEW_FILMING_REQUEST', 'Новый запрос на съемку'), ('NEW_TRAINING_REQUEST', 'Новый запрос на обучение'), ('NEW_TEAM_REQUEST', 'Новый запрос в команду')], max_length=25),
        ),
    ]
