# Generated by Django 3.2.7 on 2023-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_notifications_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_expiration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_account',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
