# Generated by Django 3.2.7 on 2023-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230422_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pro_account',
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_account',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
