# Generated by Django 3.2.7 on 2023-06-07 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230422_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('plan', models.CharField(blank=True, default=0, max_length=12, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=12, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sender', to='accounts.profile')),
            ],
        ),
    ]
