# Generated by Django 3.2.7 on 2023-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='realized',
            field=models.BooleanField(default=False),
        ),
    ]
