# Generated by Django 3.2.7 on 2022-12-21 20:25

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trainings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_rename_likesstat_gallery_likes_stat'),
        ('accounts', '0005_profile_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=50)),
                ('training_description', models.TextField(blank=True)),
                ('summary_members', models.IntegerField(default=10)),
                ('reserved_places', models.IntegerField(default=0)),
                ('place_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_ip_user', models.CharField(blank=True, max_length=18, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('was_added', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('likes_stat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('main_photo', models.ForeignKey(blank=True, null=True, on_delete=models.SET(trainings.models.get_photo), related_name='trainings_main_photo', to='gallery.image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('training_images', models.ManyToManyField(to='gallery.Image')),
                ('training_members', models.ManyToManyField(blank=True, related_name='trainings_members', to='accounts.Profile')),
                ('training_orgs', models.ManyToManyField(blank=True, related_name='trainings_orgs', to='accounts.Profile')),
                ('training_team', models.ManyToManyField(blank=True, related_name='trainings_team', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('answer_id_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_comment_answer', to='trainings.trainingscomment')),
                ('quote_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_comment_quote', to='trainings.trainingscomment')),
                ('sender_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
            ],
        ),
    ]
