# Generated by Django 3.2.7 on 2022-12-22 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_trainingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='count_interested_in',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
