# Generated by Django 3.2.7 on 2022-12-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_trainings_count_interested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='training_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_category', to='trainings.trainingcategory'),
        ),
    ]
