# Generated by Django 3.2.7 on 2022-12-22 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_trainings_training_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainings',
            name='last_ip_user',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='last_views',
        ),
        migrations.AddField(
            model_name='trainings',
            name='cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='trainings',
            name='first_payment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='trainings',
            name='string_place_location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
