# Generated by Django 3.2.7 on 2023-01-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_remove_trainings_training_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='place',
            field=models.CharField(choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], default='Оффлайн', max_length=20),
        ),
    ]
