# Generated by Django 3.2.7 on 2023-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_trainings_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='last_ip_user',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='string_place_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
