# Generated by Django 3.2.7 on 2023-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230118_0220'),
        ('trainings', '0008_auto_20230110_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='training_orgs',
            field=models.ManyToManyField(blank=True, related_name='training_orgs', to='accounts.Profile'),
        ),
    ]
