# Generated by Django 3.2.7 on 2023-01-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230118_0220'),
        ('trainings', '0010_trainingsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsrequest',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Ожидает'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='AWAITING', max_length=12),
        ),
        migrations.AlterField(
            model_name='trainingsrequest',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='trainingsrequest',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='trainings.trainings'),
        ),
    ]
