# Generated by Django 3.2.7 on 2022-05-18 12:35

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_album', models.CharField(max_length=40)),
                ('description_album', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('place_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('string_place_location', models.CharField(blank=True, max_length=40, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('photo_camera', models.CharField(blank=True, max_length=40)),
                ('focal_len', models.CharField(blank=True, max_length=40)),
                ('excerpt', models.CharField(blank=True, max_length=40)),
                ('aperture', models.CharField(blank=True, max_length=40, null=True)),
                ('iso', models.CharField(blank=True, max_length=40, null=True)),
                ('flash', models.CharField(blank=True, max_length=40)),
                ('is_sell', models.BooleanField(default=False)),
                ('last_ip_user', models.CharField(blank=True, max_length=18, null=True)),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('was_added', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_hidden', models.BooleanField(default=False)),
                ('album', models.ManyToManyField(blank=True, to='gallery.Album')),
                ('category', models.ManyToManyField(to='accounts.Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=gallery.models.image_path)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=40)),
                ('session_description', models.TextField(blank=True)),
                ('session_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('string_session_location', models.CharField(blank=True, max_length=40, null=True)),
                ('session_date', models.DateField()),
                ('last_ip_user', models.CharField(blank=True, max_length=18, null=True)),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('main_photo', models.ForeignKey(blank=True, null=True, on_delete=models.SET(gallery.models.get_photo), related_name='main', to='gallery.image')),
                ('photos', models.ManyToManyField(related_name='rel_images', to='gallery.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('session_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSessionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photosession')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSessionFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photosession')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSessionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('answer_id_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_session_comment_answer', to='gallery.photosessioncomment')),
                ('photo_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photosession')),
                ('quote_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_session_gallery_comment_quote', to='gallery.photosessioncomment')),
                ('sender_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('answer_id_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comment_answer', to='gallery.gallerycomment')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('quote_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comment_quote', to='gallery.gallerycomment')),
                ('sender_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='main_photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(gallery.models.get_photo), to='gallery.image'),
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
