# Generated by Django 3.2.7 on 2023-01-29 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230118_0220'),
        ('gallery', '0005_rename_likesstat_gallery_likes_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('mark', models.IntegerField(default=1)),
                ('content', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(to='gallery.Image')),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_profile', to='accounts.profile')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile', to='accounts.profile')),
            ],
        ),
    ]
