# Generated by Django 3.2.7 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, to='gallery.Image'),
        ),
    ]
