# Generated by Django 3.2.7 on 2022-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0002_auto_20221007_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
