# Generated by Django 3.2.7 on 2022-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0004_auto_20221007_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='current_ad',
            field=models.IntegerField(default=0),
        ),
    ]
