# Generated by Django 3.2.7 on 2022-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0005_customsettings_current_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsettings',
            name='current_ad',
            field=models.IntegerField(default=1),
        ),
    ]
