# Generated by Django 3.2.7 on 2022-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0006_alter_customsettings_current_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
