# Generated by Django 3.2.7 on 2022-10-20 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0007_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
