# Generated by Django 3.2.7 on 2022-10-20 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0008_auto_20221021_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
