# Generated by Django 3.2.7 on 2022-10-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_entities', '0015_customsettings_current_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='start',
            new_name='start_date',
        ),
    ]
